### PR TITLE
Monster/ enemy

### PR DESCRIPTION
**Pull request by manamini**
First enemy bug, may be too big to be a weaker enemy, but can worry about that later

### CODE REVIEW

**Comment by NicholasBusby** [comment]
Sorry, should have told you this.  It is much easier to handle sprites when the point to the right.  That is the default direction they handle them.  We could mirror it, but if we just make it that way in the first place it will save us some code.

**Comment by manamini** [comment]
No worries, I can quickly make another one facing the correct direction and thanks for letting me know about that

**Comment by NicholasBusby** [comment]
closing till the sprite direction is fixed.

**Comment by NicholasBusby** [comment]
Re opening here to keep the conversation in one place

**Pull request merged**
